name: run-tests
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - uses: arvsrao/googletest-action@master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
      - run: "bash tooling/test.sh"
